language: node_js
node_js:
- 11.10.1
addons:
  apt:
    packages:
    - nodejs-legacy
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
stages:
- test
before_install:
- export PATH=$PATH:$HOME/.local/bin
install:
- npm i
jobs:
  include:
  - stage: test
    name: Lint
    script: npm run lint
  - stage: test
    name: Unit test
    script: npm test
    after_success:
    - cat ./dist/js-coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
- provider: npm
  email: willem_liu@hotmail.com
  on:
    branch: master
  api_key:
    secure: DchHhyrSnU1xq8vyPnSW+i5kzwFiSvHLnDHX+9GGQi3gF7miuPTe3rnzc3U1q8wI9tTDzgE1TXCPqHTyTavakWLerE7vjOpuZJDjrVV+Oz/Pal/mC8b5VngtKo+nEvVzXJ7++6D7aDP736PTgOuH3lsxfJJB8cskNqRoXXUNnrYv/fhYA/6gFuWkqVt+369Q5PHKd9Gc1iH5JBoE71UW3q+KrA94R6BWIQXWbFEcz+cb8pogITwjiqX0buYykB1JHLxhDR6Hy6/v5Zyk2KRj7q6DDMvq4kGoC6rF473xQa5R8oVKfiooD08Pili+TNWWtqC02LxTEnv7HBB1jznYs0yxVfczUJrEEAStAXBpDGFdADcmdxNu2nQAap8RYrrpZIwv7rW0XI2nZYySiRvbKDpi9WIvT4AovyeCxLE6KndxeBjBiRodNJRH4s4enHGgPP3fLJVN1sCH0jJALVj0oXQbWQSlkYudAnHZjhxgMRB9lij2NR4GZni/fqwzTuMdb2lRvZC/5GC5Q+iaefa1Eu2SDXAn/BH0Eqn+sWr+QzttEj0kGzPcw06erfNnjwxFaFjEIxa4+MbNT5BpEgKdZMX+PfRjL8IcXGRe7LiErA/e2PXTwtVFWM1GHN7fJlCNYyeczpjOuG/k0hntpFZuAZJ1RZszPov+quqgatje6gE=
notifications:
  webhooks: https://outlook.office.com/webhook/09d65d9c-ba4d-4ce4-8ff9-985e1ea578a1@8f2a0bdd-25fe-430a-adb5-0d2367dd50ee/TravisCI/308b447ae6eb4c3f9c7e153e97a4bd25/aaeb5e7b-fe7b-4d97-9adf-3089c10da2cc
  on_success: change
