language: node_js
node_js:
  - 11.10.1
addons:
  apt:
    packages:
      - nodejs-legacy
branches:
  only:
    - master
    - "/^greenkeeper/.*$/"
stages:
  - test
  # - deploy
before_install:
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm i
  # - npm i -g now
jobs:
  include:
  - stage: test
    name: Lint
    script: npm run lint
  - stage: test
    name: Unit test
    script: npm test
    after_success:
    - cat ./dist/js-coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
#  Deploy step is unnecessary because Zeit Now is connected to the Github repository and auto-deploys.
#  - stage: deploy
#    if: branch = master
#    name: Deploy Demo
#    script: 
#      - now --scope fdmediagroep --prod --token $NOW_TOKEN
deploy:
- provider: npm
  email: willem_liu@hotmail.com
  on:
    branch: master
  api_key:
    secure: B9Z7Mlqrt+I7Vhf0ihfzfiitUgxe/On/a+aT6dNNNtdSaFwE/81Io17wc80kEfM0i0kbiobXGzs4TR9dsixxy3e5+nO+br3ZRdA8DJF6jXLhntwxbk0nPz+fzAj661hXUsR8zzPxJ7kOhczLULmtU9oVE7XcKpNH2BnCDIF4AaSmirN0zC2LYfz3TGNTSmQo7CtPSQzf8AbNgn3AFbvDXBBEI6QiWDanPCQ+6jPVoCmdZ25x2rMJes9ysnPauY8tM4WHSrryIZTXpZlhLDYC+m0mlgtucY5NQ88yjxPjzywmep1DPoLZCW/nFC7RNg7AELfrA4AH1PensfBcNYZ7LhGCGwg3hqz6oypliD+fnyCqbMf49xcj+0MVQvJm1+cDi39bjmnGSaEc0r5nJ0gxys3dQaeXwvaSNdUmmDrKCxhRNz84RNymulrqOLJuHiNcmX5AoHrwU7k0O7EUChffqAoECtevzru5HB2tSsSHT9TTml73lt1s8NMOCL3TrnBFVOaxgYxghSaaOmgCuMW7Epu+5rqt2sxZcS6n1fMKxojbuzdrqo+Q917qj65akb29KtezPelFyz6RGdCZe4YojGB70M+a5stzNEYM/xH8LSxVsAeolnc9ReYK2FyGspJkak0BGlhm4YxhQ5PRezL0EhlV7FaLE7RDqjmiHwQVHOY=
notifications:
  webhooks: https://outlook.office.com/webhook/09d65d9c-ba4d-4ce4-8ff9-985e1ea578a1@8f2a0bdd-25fe-430a-adb5-0d2367dd50ee/TravisCI/308b447ae6eb4c3f9c7e153e97a4bd25/aaeb5e7b-fe7b-4d97-9adf-3089c10da2cc
  on_success: change
